services:
  - type: web
    name: FinancialEcuadorBackend
    env: node
    plan: free
    repo: https://github.com/PIEDRACAR/FinancialEcuador
    branch: main
    buildCommand: "npm install"
    startCommand: "npm run dev"  # o "npm start" si usas producción
    autoDeploy: true

  - type: web
    name: FinancialEcuadorFrontend
    env: static
    plan: free
    repo: https://github.com/PIEDRACAR/FinancialEcuador
    branch: main
    buildCommand: "cd client && npm install && npm run build"
    staticPublishPath: "client/build"
    autoDeploy: true
